// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistic.proto

package ds.service3;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.service3.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ProductName = 1;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string ProductName = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();
}
