// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistic.proto

package ds.service3;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.service3.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ProcessMessage = 1;</code>
   */
  java.lang.String getProcessMessage();
  /**
   * <code>string ProcessMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getProcessMessageBytes();
}
